repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go.
        entry: env GOGC=25 golangci-lint run -j 8 -v ./...
        types: [go]
        language: golang
        pass_filenames: false
