# 单机模式的 redis
version: '3'
services:
  redis:
    image: redis:4.0-alpine
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
      - "--appendonly"
      - "yes"
    volumes:
      - data:/data
      - ./conf/single.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

volumes:
  data:
